export const LOGIN_REQUEST ='LOGIN_REQUEST'
export const LOGIN_SUCCESS ='LOGIN_SUCCESS'
export const LOGIN_FAIL ='LOGIN_FAIL';

export const REG_REQUEST ='REG_REQUEST'
export const REG_SUCCESS ='REG_SUCCESS'
export const REG_FAIL ='REG_FAIL';

export const LOAD_USER_REQUEST= 'LOAD_USER_REQUEST'
export const LOAD_USER_FAIL= 'LOAD_USER_FAIL'
export const LOAD_USER_SUCCESS= 'LOAD_USER_SUCCESS'


export const UPDATE_PROFILE_REQUEST= 'UPDATE_PROFILE_REQUEST'
export const UPDATE_PROFILE_FAIL= 'UPDATE_PROFILE_FAIL'
export const UPDATE_PROFILE_SUCCESS= 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_RESET= 'UPDATE_PROFILE_RESET'

export const UPDATE_PASSWORD_REQUEST= 'UPDATE_PASSWORD_REQUEST'
export const UPDATE_PASSWORD_FAIL= 'UPDATE_PASSWORD_FAIL'
export const UPDATE_PASSWORD_SUCCESS= 'UPDATE_PASSWORD_SUCCESS'
export const UPDATE_PASSWORD_RESET= 'UPDATE_PASSWORD_RESET'

export const FORGOT_PASSWORD_REQUEST= 'FORGOT_PASSWORD_REQUEST'
export const FORGOT_PASSWORD_FAIL= 'FORGOT_PASSWORD_FAIL'
export const FORGOT_PASSWORD_SUCCESS= 'FORGOT_PASSWORD_SUCCESS'


export const NEW_PASSWORD_REQUEST= 'NEW_PASSWORD_REQUEST'
export const NEW_PASSWORD_FAIL= 'NEW_PASSWORD_FAIL'
export const NEW_PASSWORD_SUCCESS= 'NEW_PASSWORD_SUCCESS'

export const LOGOUT_USER_REQUEST= 'LOGOUT_USER_REQUEST'
export const LOGOUT_USER_FAIL= 'LOGOUT_USER_FAIL'
export const LOGOUT_USER_SUCCESS= 'LOGOUT_USER_SUCCESS'

export const PENDING_REQUEST= 'PENDING_REQUEST';
export const PENDING_SUCCESS= 'PENDING_SUCCESS';
export const PENDING_FAIL= 'PENDING_FAIL';

export const PIE_DATA_REQUEST= 'PIE_DATA_REQUEST';
export const PIE_DATA_SUCCESS= 'PIE_DATA_SUCCESS';
export const PIE_DATA_FAIL= 'PIE_DATA_FAIL';

export const BAR_DATA_REQUEST= 'BAR_DATA_REQUEST';
export const BAR_DATA_SUCCESS= 'BAR_DATA_SUCCESS';
export const BAR_DATA_FAIL= 'BAR_DATA_FAIL';

export const ALL_DATA_REQUEST= 'ALL_DATA_REQUEST';
export const ALL_DATA_SUCCESS= 'ALL_DATA_SUCESS';
export const ALL_DATA_FAIL= 'ALL_DATA_FAIL';

export const COUNSELOR_DATA_REQUEST= 'COUNSELOR_DATA_REQUEST';
export const COUNSELOR_DATA_SUCCESS= 'COUNSELOR_DATA_SUCESS';
export const COUNSELOR_DATA_FAIL= 'COUNSELOR_DATA_FAIL';

export const VOLUNTEER_DATA_REQUEST = 'VOLUNTEER_DATA_REQUEST';
export const VOLUNTEER_DATA_SUCCESS = 'VOLUNTEER_DATA_SUCCESS';
export const VOLUNTEER_DATA_FAIL = 'VOLUNTEER_DATA_FAIL';

export const COUNSELORS_LIST_REQUEST= 'COUNSELORS_LIST_REQUEST';
export const COUNSELORS_LIST_SUCCESS= 'COUNSELORS_LIST_SUCESS';
export const COUNSELORS_LIST_FAIL= 'COUNSELORS_LIST_FAIL';

export const CLEAR_ERRORS ='CLEAR_ERRORS';
