export const COUNSELOR_LOGIN_REQUEST = 'COUNSELOR_LOGIN_REQUEST';
export const COUNSELOR_LOGIN_SUCCESS = 'COUNSELOR_LOGIN_SUCCESS';
export const COUNSELOR_LOGIN_FAIL = 'COUNSELOR_LOGIN_FAIL';

export const COUNSELOR_REG_REQUEST = 'COUNSELOR_REG_REQUEST';
export const COUNSELOR_REG_SUCCESS = 'COUNSELOR_REG_SUCCESS';
export const COUNSELOR_REG_FAIL = 'COUNSELOR_REG_FAIL';

export const COUNSELOR_LOAD_USER_REQUEST = 'COUNSELOR_LOAD_USER_REQUEST';
export const COUNSELOR_LOAD_USER_FAIL = 'COUNSELOR_LOAD_USER_FAIL';
export const COUNSELOR_LOAD_USER_SUCCESS = 'COUNSELOR_LOAD_USER_SUCCESS';

export const COUNSELOR_UPDATE_PROFILE_REQUEST = 'COUNSELOR_UPDATE_PROFILE_REQUEST';
export const COUNSELOR_UPDATE_PROFILE_FAIL = 'COUNSELOR_UPDATE_PROFILE_FAIL';
export const COUNSELOR_UPDATE_PROFILE_SUCCESS = 'COUNSELOR_UPDATE_PROFILE_SUCCESS';
export const COUNSELOR_UPDATE_PROFILE_RESET = 'COUNSELOR_UPDATE_PROFILE_RESET';

export const COUNSELOR_UPDATE_PASSWORD_REQUEST = 'COUNSELOR_UPDATE_PASSWORD_REQUEST';
export const COUNSELOR_UPDATE_PASSWORD_FAIL = 'COUNSELOR_UPDATE_PASSWORD_FAIL';
export const COUNSELOR_UPDATE_PASSWORD_SUCCESS = 'COUNSELOR_UPDATE_PASSWORD_SUCCESS';
export const COUNSELOR_UPDATE_PASSWORD_RESET = 'COUNSELOR_UPDATE_PASSWORD_RESET';

export const COUNSELOR_FORGOT_PASSWORD_REQUEST = 'COUNSELOR_FORGOT_PASSWORD_REQUEST';
export const COUNSELOR_FORGOT_PASSWORD_FAIL = 'COUNSELOR_FORGOT_PASSWORD_FAIL';
export const COUNSELOR_FORGOT_PASSWORD_SUCCESS = 'COUNSELOR_FORGOT_PASSWORD_SUCCESS';

export const COUNSELOR_NEW_PASSWORD_REQUEST = 'COUNSELOR_NEW_PASSWORD_REQUEST';
export const COUNSELOR_NEW_PASSWORD_FAIL = 'COUNSELOR_NEW_PASSWORD_FAIL';
export const COUNSELOR_NEW_PASSWORD_SUCCESS = 'COUNSELOR_NEW_PASSWORD_SUCCESS';

export const COUNSELOR_LOGOUT_USER_REQUEST = 'COUNSELOR_LOGOUT_USER_REQUEST';
export const COUNSELOR_LOGOUT_USER_FAIL = 'COUNSELOR_LOGOUT_USER_FAIL';
export const COUNSELOR_LOGOUT_USER_SUCCESS = 'COUNSELOR_LOGOUT_USER_SUCCESS';

export const CLEAR_ERRORS ='CLEAR_ERRORS';
