export const QUESTION_REQUEST = 'QUESTION_REQUEST';
export const QUESTION_FAIL = 'QUESTION_FAIL';
export const QUESTION_SUCCESS = 'QUESTION_SUCCESS';

export const SUBMISSION_REQUEST = 'SUBMISSION_REQUEST';
export const SUBMISSION_FAIL = 'SUBMISSION_FAIL';
export const SUBMISSION_SUCCESS = 'SUBMISSION_SUCCESS';

export const CLEAR_ERRORS ='CLEAR_ERRORS';